# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.SlugField(default=uuid.uuid1, unique=True)),
                ('is_url_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remembering.Person'),
        ),
    ]
