# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-02 10:31
from __future__ import unicode_literals

import Remembering.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remembering', '0002_auto_20160815_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Remembering.models.get_file_path),
        ),
    ]
